name: Levensgewijs
favicon: null
layout_spectrum: 0.55941
typography_spectrum: 0.706312351860106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.038976303301751614
  saturation: 0.8523263942915946
  rhythmicContrast: 0.43839387549087405
purpose: []
